name: This a docker image workflow  
on: 
  push: # When pushing to any branch then run this action.
    branches: [main]
  pull_request:
    branches: [main]
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - uses: actions/checkout@v3 # first action : checkout source code
    - name: docker login
      run: |
        $ echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER foo --password-stdin  
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag python-docker-image:$(date +%s)
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME
